components/00-base/_variables.components.scss
components/03-organisms/promo/promo.scss
components/03-organisms/promo/promo.stories.js
components/03-organisms/promo/promo.twig

closes https://github.com/civictheme/uikit/issues/79
1. Updated the markup to use the same approach as what Basic component uses - containment
2. Added  props to the Storybook story ( Contained & With background)

[#79] Updated markup and prop for Promo component to be Contained or not.

---

.storybook/addon-config.js
.storybook/preview.js
package.json
patches/@whitespace+storybook-addon-html+5.1.6.patch

closes https://github.com/civictheme/uikit/issues/83
1. Added https://github.com/whitespace-se/storybook-addon-html
2. Added patch to fix issue https://github.com/whitespace-se/storybook-addon-html/issues/102

#83 Updated storybook to show HTML source.

---

components/00-base/_variables.components.scss
components/03-organisms/navigation/navigation.scss
components/03-organisms/navigation/navigation.twig

https://www.drupal.org/project/civictheme/issues/3422805
1. Updated navigation to remove child items when dropdown is set to none.
2. Added missing styles for navigation when when dropdown is set to none.
Before: 
After:

BC: Fixed navigation menu when 'Dropdown type is set to 'None'.

---

components/03-organisms/navigation/navigation.scss

1. Fixed background not applying to navigation of type 'dropdown'.

Fixed background not applying to navigation of type 'dropdown'.

---

components/00-base/collapsible/collapsible.js

Closes https://github.com/civictheme/uikit/issues/62
1. Fixed Collapsible acts differently on spacebar and enter keys.

[#62] Fixed closing of the descendant  item with a keyboard collapsing ancestor items in Side Navigation component.

---

components/00-base/collapsible/collapsible.js

Closes https://github.com/civictheme/uikit/issues/62
1. Fixed For navigation, accordion and side bar components - UP does not close open menu/accordion.
https://nimb.ws/kouGV6B

[#62] Fixed For navigation, accordion and side bar components - UP does not close open menu/accordion.

---

components/00-base/collapsible/collapsible.js
components/01-atoms/button/button.js
components/01-atoms/popover/popover.twig
components/02-molecules/group-filter/group-filter.js
components/02-molecules/group-filter/group-filter.stories.js
components/02-molecules/single-filter/single-filter.js
components/02-molecules/single-filter/single-filter.stories.js

Closes https://github.com/civictheme/uikit/issues/78 
1. [x] Fixed: The filters and options are read by a screenreader left to right, top to bottom (e.g. first row left to right and then second row left to right).
2. [x] Fixed: The focus is visible on each select box in drop down when navigating using a mouse or keyboard.
3. [x] Fixed: The user can tab to each interactive element and interact with the filter using keyboard or mouse.
4. [x] Fixed: If the contents underneath the filter change when an option is selected, the change should be announced using aria-live=”polite” - FAIL.

[#78] Fixed Single and Group filter announcing changes to content and a "down" key trigger for collapsible.

---

components/00-base/flyout/flyout.js

Closes https://github.com/civictheme/uikit/issues/69
1. Added Tabbing in Flyout component to “cycle” back to the first component instead of going to the page behind it.
https://nimb.ws/sF4IT0g

[#69] Fixed TAB-out from the mobile menu is not working.

---

components/00-base/_variables.components.scss
components/00-base/mixins/_image.scss
components/03-organisms/campaign/campaign.scss
components/03-organisms/campaign/campaign.stories.js
components/03-organisms/campaign/campaign.twig

[#156] Updated Campaign to use square image within a container of equal widths.

---

components/00-base/_variables.components.scss
components/02-molecules/navigation-card/navigation-card.scss
components/02-molecules/navigation-card/navigation-card.stories.js

Closes #172 
**With link**
**Without link - colour remains**

[#172] Fixed Icon colour on Navigation card.

---

components/00-base/_variables.components.scss
components/00-base/base.utils.js
components/01-atoms/select/select.scss
components/01-atoms/select/select.stories.js
components/01-atoms/select/select.twig

[#150] Updated Select styles to designs from 1.8

---

components/00-base/_variables.components.scss

Closes https://github.com/civictheme/uikit/issues/201#issuecomment-2166229011
1. Fixed Left stripe missing for child active items for both themes for side navigation component.

[#201] Fixed Left stripe missing for child active items for both themes for side navigation component.

---

components/01-atoms/label/label.scss

The problem:
https://github.com/civictheme/uikit/assets/378794/975e7f9e-2b49-4886-ac92-e9c795647502

Fixed label background flickering when tapped on mobile webkit-based browsers.

---

components/00-base/layout/layout.scss

- Fixed column gaps to be larger when only a single sidebar is present.
- Updated `grid-gap` to `gap` as [docs](https://developer.mozilla.org/en-US/docs/Web/CSS/gap) say `grid-gap` is a legacy alias.
- Fixed grid ordering not applying due to double .ct-layout__inner.
https://github.com/civictheme/uikit/assets/12739575/da00c35f-f29b-4def-9904-12fdbca9c373

Fixed column gaps to be larger when only a single sidebar is present.

---

components/01-atoms/input/input.scss
components/02-molecules/field/field.utils.js

Fixed browser-provided icon colour on `Input`.

---

components/00-base/layout/layout.js
components/00-base/layout/layout.scss
components/00-base/layout/layout.stories.js

1.  Fixed sidebar gap on layout using masonry with JS fallback.
2.  The JS is not a general masonry polyfill, it has been written explicitly to support our use case of both sidebars with top and bottom regions showing - this is to reduce the amount of processing and code required.
3.  The JS fallback has a number of checks in place to avoid needing to redraw anything unnecessarily:
1.  The fallback is initialized only once on the layout grid.
2.  The grid must not have enabled masonry (native support must not be working).
3.  The height of the grid must change before a redraw occurs.
https://github.com/civictheme/uikit/assets/12739575/87bd3d16-76fb-4893-9b15-94944930129 …

Fixed sidebar gap on `Layout` using masonry with JS fallback.

---

components/00-base/_variables.components.scss
components/02-molecules/field/field.scss
components/02-molecules/field/field.stories.js

https://github.com/civictheme/uikit/issues/277
https://github.com/civictheme/uikit/issues/279
1. Added `ct-field-horizontal-label-fixed-width-25` utility class.
2. This class can be added on the parent form element, and will set a width (of 25 * 8) on any child labels of horizontal fields (vertical fields are unaffected).
3. The available field spacings can be configured by overriding the base variable: `$ct-field-horizontal-label-fixed-widths: 10, 20, 30, 40` to whatever sizes are required.
4. Currently there is no test page in storybook for this, screenshot taken from a demo page set up locally.
5. Added a page `Field/Field Examples` to test field groups.
1. Go to …

[#277] Added fixed width utility class to size labels consistently.

---

components/02-molecules/pagination/__snapshots__/pagination.test.js.snap
components/02-molecules/pagination/pagination.stories.js
components/02-molecules/pagination/pagination.twig

[#280] Fixed pagination and removed `active_is_link` prop.

---

components/00-base/layout/layout.js
components/00-base/layout/layout.stories.js
components/00-base/layout/layout.stories.scss
components/00-base/storybook/storybook.generators.utils.js
components/00-base/storybook/storybook.generators.utils.test.js

closes #308
This PR changes 2 things:
1. We are no longer observing the grid's items - we are observing grid's items' children to track the change of their heigh.
2. The selection of the grid elements is now scoped to the immediate children to allow binding to nested layouts correctly.
https://github.com/civictheme/uikit/assets/378794/72b69d25-f6c2-4b43-ad4c-a83b06451359

[#308] Fixed Layout masonry is not applied when nested Layout is used.

---

components/00-base/layout/layout.scss

[#309] Fixed `Layout` gaps for nested layouts.

---

components/00-base/grid/grid.scss
components/00-base/grid/grid.stories.js
components/00-base/mixins/_grid.scss

Fixed margins on the nested fluid grid.

---

components/00-base/_variables.components.scss
components/02-molecules/back-to-top/back-to-top.scss

Closes #321
1. Added SCSS variable to set a border color for back-to-top component.
2. Made the default the background color (same as existing implementation).

[#321] Added SCSS var to set a border color for back-to-top component.

---

components/02-molecules/event-card/__snapshots__/event-card.test.js.snap
components/02-molecules/event-card/event-card.twig
components/02-molecules/promo-card/__snapshots__/promo-card.test.js.snap
components/02-molecules/promo-card/promo-card.twig

https://github.com/civictheme/uikit/issues/330
1. Ignore arrow links from tabbing and screen readers.

[#330] Fixed card link arrows being read-out by screen readers and tabbed to.

---

components/02-molecules/table-of-contents/table-of-contents.js

Closes https://github.com/civictheme/uikit/issues/336
1. Added a check to  remove duplicates when `data-table-of-contents-anchor-scope-selector` may have duplicated clases

[#336] H2s are displaying twice in Table of contents (TOC)

---

components/02-molecules/logo/logo.twig
components/02-molecules/tabs/tabs.twig
components/02-molecules/video-player/video-player.twig
components/03-organisms/navigation/navigation.twig
components/03-organisms/webform/webform.twig

These changes were taken from: https://git.drupalcode.org/project/demo_design_system/-/merge_requests/3/
1. Consistent and correct spelling of 'boolean', indentation, types.

[#342] Twig comment changes required for generating components.

---

components/02-molecules/back-to-top/__snapshots__/back-to-top.test.js.snap
components/02-molecules/back-to-top/back-to-top.twig
components/04-templates/page/__snapshots__/page.test.js.snap

https://github.com/civictheme/uikit/issues/359
1. Added visually hidden text to read out on back-to-top button.

[#359] Added visually hidden text to read out on back-to-top button.

---

components/00-base/mixins/_content-link.scss

In Figma, the underline is `1px`, but in UIKit it is erroneously `2px`.
Before:
After:

[#392] Fixed Content Link underline thickness.

---

components/01-atoms/button/__snapshots__/button.test.js.snap
components/01-atoms/button/button.twig
components/02-molecules/callout/__snapshots__/callout.test.js.snap
components/02-molecules/map/__snapshots__/map.test.js.snap
components/02-molecules/social-links/__snapshots__/social-links.test.js.snap
components/02-molecules/video-player/__snapshots__/video-player.test.js.snap
components/03-organisms/campaign/__snapshots__/campaign.test.js.snap
components/03-organisms/promo/__snapshots__/promo.test.js.snap

https://github.com/civictheme/uikit/issues/389
1. The aria-label in this case would override whatever text was present within the button, meaning buttons lose context if used with a screen reader.

[#389] Removed aria-label from button with 'is_new_window'.

---

components/04-templates/page/__snapshots__/page.test.js.snap
components/04-templates/page/page.twig

this is a tricky one
The Skip link skips to the `main-content` anchor. This anchor is set within the Banner to allow including of the page heading into what is considered to be a "whole page content".
On the pages where the banner is not present (if a banner is replaced by another component, for example), the anchor is not rendered.
This PR adds the anchor on the page if the banner is not present.

Fixed skip link having no target when Banner is not on the page.

---

components/00-base/_variables.components.scss

Closes #364 
UIKit already had a focus state, but it was set to transparent as per designs - the design does not have a focus state.

[#364] Added focus state for Back-to-Top link.

---

components/00-base/_variables.components.scss

#322 added CSS var to set a border and defaulted the border to the colour of the button background to match the current designs.
But on the client sites there is almost always a need to set the border colour to make this component appear visually contrasting to the dark footer (where this component often appears).
This PR updates the default colour value used for the border to match the lightest background colour: this means that the border will not be visible on the light page content but will be in a contrast on footer.

Added default border colour for Back-To-Top.

---

components/01-atoms/fieldset/fieldset.twig
components/02-molecules/field/__snapshots__/field.test.js.snap
components/02-molecules/field/field.twig
components/02-molecules/pagination/__snapshots__/pagination.test.js.snap

https://github.com/civictheme/monorepo-drupal/pull/1306
1. Added fix to support Form element prefix & suffix.

Add prefix and suffix variables to form elements.

---

components/02-molecules/field/field.twig

1. Added fix to support label in Form element.

Added fix to support label in Form element.

---

components/00-base/collapsible/collapsible.js

1. Added default state of collapsed.

[#358] Added default state of collapsed.

---

components/00-base/collapsible/collapsible.js

1. Fixed sub-navigation active tabindex.

[#370] Fixed sub-navigation active tabindex.

---

components/00-base/mixins/_content-link.scss
components/00-base/mixins/_content.scss
components/00-base/mixins/_image.scss
components/01-atoms/content-link/content-link.scss
components/01-atoms/iframe/iframe.scss
components/01-atoms/input/input.scss
components/02-molecules/navigation-card/navigation-card.scss
components/02-molecules/subject-card/subject-card.scss

- Fix subject card box-sizing.
- Fix input box-sizing.
- Fix navigation card box-sizing.
- Fix campaign image box-sizing.
- Fix iframe with background box-sizing.
- Updated links in accordion to properly set light / dark.
I have not made any changes to slider as it is currently being worked on in https://github.com/civictheme/uikit/issues/294

[#392] Fixed inline css dependency issues.

---

components/03-organisms/message/__snapshots__/message.test.js.snap
components/03-organisms/message/message.test.js
components/03-organisms/message/message.twig

Closes https://github.com/civictheme/uikit/issues/356
1. Add the aria-live="assertive" attribute to the < div > element that contains the status message.

[#356] WCAG 4.1.3 AA: Success message not announced by screen readers (Issue 37)

---

components/01-atoms/link/__snapshots__/link.test.js.snap
components/01-atoms/link/link.test.js
components/01-atoms/link/link.twig
components/01-atoms/popover/__snapshots__/popover.test.js.snap
components/02-molecules/navigation-card/__snapshots__/navigation-card.test.js.snap
components/02-molecules/next-step/__snapshots__/next-step.test.js.snap
components/02-molecules/promo-card/__snapshots__/promo-card.test.js.snap
components/02-molecules/service-card/__snapshots__/service-card.test.js.snap
components/02-molecules/snippet/__snapshots__/snippet.test.js.snap
components/02-molecules/subject-card/__snapshots__/subject-card.test.js.snap

https://github.com/civictheme/uikit/issues/436
1. Removed aria-label from link with 'is_new_window'. See issue for reasoning.

[#436] Removed aria-label from link with 'is_new_window'.

---

components/00-base/collapsible/collapsible.js
components/00-base/collapsible/collapsible.stories.twig
components/00-base/collapsible/collapsible.test.js
components/03-organisms/navigation/__snapshots__/navigation.test.js.snap
components/03-organisms/navigation/navigation.twig

https://github.com/civictheme/uikit/issues/425
1. While links now use text-icon to group the last word with the icon to allow for both to wrap together, this does not happen on the menu because the icon is added through javascript, and not through the twig template. This change adds wrapping when the `data-collapsible-icon-group` attribute is applied to a collapsible element.

[#425] Group last word and icon in collapsible script.

---

components/00-base/menu/__snapshots__/menu.test.js.snap
components/00-base/menu/menu.test.js
components/00-base/menu/menu.twig

- Github: Fixed https://github.com/civictheme/uikit/issues/357
- Jira: https://salsadigital.atlassian.net/browse/CIVIC-2010
1. Fixed link has invalid state
2. Updated menu test

[#357] Fixed link has invalid state

---

components/03-organisms/message/__snapshots__/message.test.js.snap
components/03-organisms/message/message.test.js
components/03-organisms/message/message.twig

1. Updated `aria-live` for error message to `assertive`.

[#356] Updated aria-live for error message to assertive.

---

components/03-organisms/slider/slider.js

Fixed: https://github.com/civictheme/uikit/issues/367
1.  Remove focus for inactive slider item using `inert` attribute.
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inert
N/A

[#367] Remove focus for inactive slider item.

---

components/03-organisms/slider/slider.js

1. Slider will often render before fonts have loaded. In this case a font may change the content size of a slide, and cause the height calculations to be incorrect. By calling resize after fonts have loaded, we ensure that the slides are correctly size if custom fonts are being used.

[#468] Resize slider on font load.

---

.storybook/preview.js
build.js
package.json

1. Create a `civictheme.storybook.css` file which replaces the `/theme/custom/MYTHEME/dist/assets/` path with `/assets/`, which is suitable for the storybook. 
2. Currently this only runs for the main stylesheet. `.editor`, `.layout` are not used in storybook. `.stories` is only used in storybook, so this will use the `/assets/` path by default.

Fixed an issue in storybook, where the asset directory cannot be found.

---

components/00-base/collapsible/collapsible.js
components/00-base/collapsible/collapsible.scss

https://salsadigital.atlassian.net/browse/CIVIC-1820
https://github.com/civictheme/uikit/issues/228
1. Collapsible now applies styles directly to active trigger, allowing only the opening trigger to animate.
2. Removed unnecessary use statements from collapsible styles.
3. Restructured trigger styles to (mostly) share the same trigger selector.
4. Fixed collapsed panels not opening when in print styles.
https://github.com/user-attachments/assets/94fd2749-3af4-4a8a-82e7-1ba6dae7f424

[#228] Fixed unwanted cascading styles when toggling collapsible.

---

components/03-organisms/banner/__snapshots__/banner.test.js.snap
components/03-organisms/banner/banner.twig
components/04-templates/page/__snapshots__/page.test.js.snap
components/04-templates/page/page.test.js
components/04-templates/page/page.twig

https://github.com/civictheme/uikit/issues/355
1. Removed empty `<a>` for skipping to main-content.
2. Added main-content id to banner root element (if available) or main if no banner available. Banner already has id set from drupal, so PR to remove the second id is [here](https://github.com/civictheme/monorepo-drupal/pull/1354).
3. Removed empty `<a>` for banner - this looks like a remnant of an old implementation. See notes below.
**Note on banner skip link removal:**
Looking into why this empty anchor existed when it didn't seem to be used, I found the following:
It was originally part of an accessibility fix where skip link would point to the banner element, then …

[#355] Updated skip link to use id on the main, or banner element.

---

README.md
package-lock.json
packages/sdc/components/00-base/background/background.utils.js
packages/sdc/components/00-base/collapsible/collapsible.test.js
packages/sdc/components/00-base/icon/icon.utils.js
packages/sdc/components/02-molecules/logo/logo.utils.js
packages/sdc/scripts/install.sh

Some fixes for the uikit restructure
- Fix paths for sdc install script.
- Ignore YML files when copying components from twig into sdc
- Added arm64 packages in package-lock. This fixes build (SASS) and Storybook (rollup) errors when running npm commands on ARM devices.
- Re-copied component twig to sdc - seems some lint fixes weren't synced.

Fixes for SDC sync, Apple Silicon builds and spelling.

---

components/00-base/mixins/_font.scss

This was added in 2021 when IE <10 was still relevant in government orgs. This is [no longer the case](https://en.wikipedia.org/wiki/Usage_share_of_web_browsers) and this IE hack can be safely removed.
1. Removed an additional `src` attribute added for `eot` fonts used to account for IE <10.
[Spec of @font-face`](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face#syntax)

Removed legacy @font-face `src` attribute used in IE <10.
