.github/workflows/test.yml

[#68] Added deployment to Netlify.

---

components/00-base/_variables.components.scss
components/00-base/mixins/_table.scss
components/01-atoms/table/table.stories.js

closes https://github.com/civictheme/uikit/issues/90
1. Updated content in table cells to be top aligned.

#90 Updated content in table cells to be top aligned.

---

components/02-molecules/next-step/next-step.twig
components/03-organisms/campaign/campaign.twig
components/03-organisms/slider/slide.twig

1. Added is_external property to links in campaign component.

[#92] Added is_external property to link object in campaign component.

---

components/00-base/mixins/_content.scss
components/02-molecules/basic-content/basic-content.stories.js

Closes https://github.com/civictheme/uikit/issues/47
1. Updated the presentation of indented UL and OL children

[#47] Updated the presentation of indented UL and OL children

---

components/01-atoms/link/link.twig

1. Added condition to check for external links.

Fixed Next step component: Two link arrows are displayed.

---

components/03-organisms/slider/slider.stories.js

Fixed Broken Slider.

---

.github/workflows/test.yml

[#160] Added NodeJS 22 build to CI.

---

components/02-molecules/table-of-contents/table-of-contents.stories.js

[#154] Fixed TOC not appearing in Storybook.

---

components/03-organisms/banner/banner.stories.js
components/03-organisms/banner/banner.twig

[#155] Fixed missing Banner background in Storybook and added support for `alt` attribute.

---

.github/workflows/test.yml
.gitignore
.twig-cs-fixer.php
components/01-atoms/table/table.twig
components/03-organisms/navigation/navigation.twig
composer.json

Added Twig CS Fixer.

---

components/03-organisms/alert/alert.stories.js

[#152] Fixed Alert API storybook page.

---

components/03-organisms/banner/banner.stories.js
components/03-organisms/banner/banner.stories.twig

Allow to set Content and Content below theme in Banner story.

---

components/00-base/mixins/_image.scss
components/02-molecules/navigation-card/navigation-card.scss

[#169] Fixed image as icon on Navigation card.

---

.storybook/preview.js
components/00-base/_variables.components.scss
components/00-base/base.stories.scss
components/00-base/base.utils.js
components/00-base/item-grid/item-grid.scss
components/02-molecules/navigation-card/navigation-card.scss
components/02-molecules/navigation-card/navigation-card.stories.js
components/03-organisms/list/list.stories.js

[#73] Updated Navigation card to change orientation to vertical in narrow columns of `List`.

---

components/02-molecules/single-filter/single-filter.js
components/02-molecules/single-filter/single-filter.scss
components/02-molecules/single-filter/single-filter.stories.js
components/02-molecules/single-filter/single-filter.twig

Closes #184 
https://github.com/civictheme/uikit/assets/378794/843ddc3f-f4b9-4823-b84d-d77391a6c3f3

[#184] Added reset button and disabling of the buttons if none of the Chips is selected in Single filter.

---

components/02-molecules/single-filter/single-filter.scss
components/02-molecules/single-filter/single-filter.twig

https://github.com/civictheme/uikit/assets/378794/d434b8af-d875-4ab8-b6c3-a986ae28b6fc

Fixed buttons growing in the Single filter.

---

components/00-base/base.utils.js
components/03-organisms/list/list.stories.js

[#198] Fixed incorrectly sets URLs and dates on cards in List stories.

---

components/00-base/_variables.base.scss
components/00-base/_variables.components.scss
components/00-base/base.utils.js
components/00-base/colors/colors.stories.scss
components/00-base/mixins/_content.scss
components/00-base/mixins/_typography.scss
components/01-atoms/button/button.scss
components/01-atoms/label/label.scss
components/01-atoms/radio/radio.scss
components/01-atoms/radio/radio.stories.js
components/01-atoms/radio/radio.twig
components/01-atoms/tag/tag.scss
components/02-molecules/figure/figure.scss
components/02-molecules/table-of-contents/table-of-contents.scss
components/02-molecules/tooltip/tooltip.scss
components/03-organisms/alert/alert.scss
components/03-organisms/mobile-navigation/mobile-navigation.scss

Closes #80.
https://github.com/civictheme/uikit/assets/378794/523eeebd-e130-4a40-8f62-137853e21d2b

[#80] Updated `Radio` colours and dimensions.

---

components/00-base/_variables.components.scss
components/00-base/mixins/_image.scss
components/01-atoms/checkbox/checkbox.scss
components/01-atoms/checkbox/checkbox.stories.js
components/01-atoms/checkbox/checkbox.twig
components/01-atoms/radio/radio.scss

Closes #67
https://github.com/civictheme/uikit/assets/378794/173ecb42-2db1-4c4d-b2a4-b10bc36a29ec

[#67] Updated checkbox to use SVG mask.

---

.storybook/addon-config.js
components/01-atoms/checkbox-group/checkbox-group.stories.js
components/01-atoms/checkbox/checkbox.stories.js
components/01-atoms/field-description/field-description.stories.js
components/01-atoms/field-message/field-message.stories.js
components/01-atoms/fieldset/fieldset.stories.js
components/01-atoms/label/label.stories.js
components/01-atoms/radio-group/radio-group.stories.js
components/01-atoms/radio/radio.stories.js
components/01-atoms/select/select.stories.js
components/01-atoms/textarea/textarea.stories.js
components/01-atoms/textfield/textfield.stories.js
package.json

Moved all Form-related stories to `Form Controls` folder.

---

components/03-organisms/side-navigation/side-navigation.scss

Closes https://github.com/civictheme/uikit/issues/201
1. Updated variable names reference.

[#201] Fixed Side Navigation is missing left stripe.

---

components/00-base/base.utils.js
components/00-base/scrollspy/scrollspy.stories.js
components/03-organisms/back-to-top/back-to-top.stories.js

Updated `Back to Top` and added `Scrollspy` docs.

---

components/00-base/_variables.base.scss
components/00-base/grid/grid.scss
components/00-base/grid/grid.stories.js
components/00-base/grid/grid.stories.scss
components/00-base/storybook/storybook.container.utils.stories.scss
components/00-base/storybook/storybook.placeholder.utils.stories.scss

https://github.com/civictheme/uikit/assets/378794/00864545-66f2-49d4-a37c-61840eda57ea

Added responsive vertical spacing to `Grid`.

---

components/00-base/flex/_index.scss
components/00-base/grid/grid.scss
components/00-base/mixins/_image.scss
components/03-organisms/banner/banner.scss
components/03-organisms/campaign/campaign.scss
components/03-organisms/campaign/campaign.twig

Updated `Campaign` to the latest designs.

---

components/00-base/_variables.components.scss
components/00-base/mixins/_highlight.scss
components/01-atoms/fieldset/fieldset.scss
components/01-atoms/fieldset/fieldset.stories.js
components/01-atoms/fieldset/fieldset.twig
components/02-molecules/field/field.utils.js

https://github.com/civictheme/uikit/assets/378794/8f8f9c4c-c535-49f0-a2e2-bf38548eeb1d

Added support for a nested `Fieldset`.

---

components/00-base/_variables.components.scss
components/01-atoms/input/input.scss
components/01-atoms/input/input.stories.js
components/01-atoms/input/input.twig
components/02-molecules/field/field.scss
components/02-molecules/field/field.stories.js
components/02-molecules/field/field.twig

https://github.com/civictheme/uikit/issues/246

Added generic `Input` form control.

---

components/00-base/layout/layout.scss
components/00-base/layout/layout.stories.js

Updated `Layout` to be limited only to the inner layout.

---

components/01-atoms/checkbox/__snapshots__/checkbox.test.js.snap
components/01-atoms/field-description/field-description.twig
components/01-atoms/field-message/field-message.twig
components/01-atoms/fieldset/__snapshots__/fieldset.test.js.snap
components/01-atoms/label/__snapshots__/label.test.js.snap
components/01-atoms/label/label.stories.js
components/01-atoms/label/label.test.js
components/01-atoms/label/label.twig
components/01-atoms/paragraph/paragraph.twig
components/01-atoms/radio/__snapshots__/radio.test.js.snap
components/02-molecules/field/__snapshots__/field.test.js.snap
components/02-molecules/pagination/__snapshots__/pagination.test.js.snap
components/02-molecules/single-filter/__snapshots__/single-filter.test.js.snap

[#273] Added `allow_html` to `Label` component.

---

components/00-base/_variables.components.scss
components/02-molecules/field/field.scss
components/02-molecules/field/field.stories.js

Added label width to stories.

---

components/02-molecules/field/field.scss
components/02-molecules/field/field.stories.js

1. Update the Field's SCSS to set that line height.

Update the Field's SCSS to set that line height.

---

components/01-atoms/table/table.js

Closes https://github.com/civictheme/uikit/issues/329
1. Perform additional check that header cell exists before trying to access it's variables.

[#329] Fixed table error when head and body cell count aren't aligned.

---

components/00-base/grid/__snapshots__/grid.test.js.snap
components/00-base/grid/grid.twig
components/02-molecules/field/field.twig

https://www.drupal.org/project/demo_design_system/issues/3469075
1. As per discovered issues, removed the unused variables.

Remove unused variables in twig.

---

components/01-atoms/input/input.scss
components/01-atoms/textfield/textfield.scss

1. Updated textfield input padding

[#417] Updated textfield input padding.

---

components/03-organisms/header/header.stories.js
components/03-organisms/navigation/__snapshots__/navigation.test.js.snap
components/03-organisms/navigation/navigation.stories.js
components/03-organisms/navigation/navigation.twig

1. Wrapped menu within a `<nav>` element with `aria-label` attribute.

[#380] Added <nav> element.

---

components/01-atoms/textfield/textfield.scss

- https://salsadigital.atlassian.net/browse/CIVIC-1972
1. Fixed textfield width

[#417] Fixed textfield width.

---

components/00-base/_variables.components.scss
components/03-organisms/slider/slide.twig
components/03-organisms/slider/slider.js
components/03-organisms/slider/slider.scss

This reverts commit 6518c1cc5278ceba6b421326ec76e787611ff7f0.
1. Revert fix as causes other problems.

Revert "[#294]  Slider is broken when large images are used."

---

components/03-organisms/footer/__snapshots__/footer.test.js.snap
components/03-organisms/footer/footer.stories.js
components/03-organisms/footer/footer.test.js
components/03-organisms/footer/footer.twig
components/03-organisms/navigation/navigation.scss
components/04-templates/page/__snapshots__/page.test.js.snap

Added a slot to the Footer for a horisontal navigation.

---

components/00-base/menu/__snapshots__/menu.test.js.snap
components/00-base/menu/menu.twig
components/03-organisms/navigation/__snapshots__/navigation.test.js.snap
components/03-organisms/side-navigation/__snapshots__/side-navigation.test.js.snap

Fixed https://github.com/civictheme/uikit/issues/376
1. Added aria-current for menu active item.

[#376] Added aria-current for menu active item.

---

.github/workflows/test.yml
components/03-organisms/footer/footer.twig

1. Removed duplicate footer region

Fixed duplicate twig block.

---

components/03-organisms/slider/slider.js

1. Fixed the inactive item focusing issue.

[#294] Updated inactive item.

---

.github/workflows/test.yml
components-sdc/components/02-molecules/group-filter/group-filter.twig
components/02-molecules/group-filter/group-filter.twig
package.json
scripts/snapshot-diff.sh
visual-diff/lib/screenshot.mjs

1. Added script to compare snapshots between components and components-sdc.

Added snapshot comparison command and test.

---

.github/workflows/test.yml

1. Added second workflow to deploy second site to netlify.

Added netlify job to publish sdc storybook.

---

packages/sdc/components/00-base/mixins/_grid.scss
packages/sdc/components/03-organisms/navigation/navigation.css
packages/twig/components/00-base/mixins/_grid.scss

Issue Link: https://github.com/civictheme/uikit/issues/590
1. Fix 0 width container on mobile due to xs breakpoint of 0 width.

[#590] Fixed 0 width container on mobile due to xs breakpoint of 0 width.
